export const newItemActionTypes = {
    ADD_NEW_ITEM_START: 'ADD_NEW_ITEM_START',
    ADD_NEW_ITEM_SUCCESS: 'ADD_NEW_ITEM_SUCCESS',
    ADD_NEW_ITEM_FAILURE: 'ADD_NEW_ITEM_FAILURE',
    UPDATE_ITEM_START: 'UPDATE_ITEM_START',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILURE: 'UPDATE_ITEM_FAILURE'
}